/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  supremeGuidelines: [
    {
      type: 'category',
      label: 'Supreme Guidelines',
      collapsible: false,
      collapsed: false,
      items: [
        'supreme/intro',
        {
          type: 'category',
          label: 'Foundation Information',
          items: [
            {
              type: 'autogenerated',
              dirName: 'supreme/foundation_information',
            },
          ]
        },
        {
          type: 'category',
          label: 'Information Security',
          items: [
            {
              type: 'autogenerated',
              dirName: 'supreme/information_security',
            },
          ]
        },
        {
          type: 'category',
          label: 'Miscellaneous Policies',
          items: [
            {
              type: 'autogenerated',
              dirName: 'supreme/miscellaneous_information',
            },
          ]
        },
        {
          type: 'category',
          label: 'Foundation Laws & Policies',
          items: [
            {
              type: 'autogenerated',
              dirName: 'supreme/law_and_policies',
            },
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Hostage Regulations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'hostage_regulations',
        },
      ]
    },
    {
      type: 'category',
      label: 'Red Heron Regulations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'red_heron_regulations',
        },
      ]
    },
    {
      type: 'category',
      label: 'Raid Regulations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'raid_regulations',
        },
      ]
    },
  ],
  departmentGuidelines: [    {
    type: 'category',
    label: 'Departmental Guidelines',
    collapsible: false,
    collapsed: false,
    items: [
      'departments/intro',
      {
        type: 'category',
        label: 'Security Department',
        items: [
          {
            type: 'autogenerated',
            dirName: 'departments/security_department',
          },  
        ]
      },
      {
        type: 'category',
        label: 'Medical Department',
        items: [
          {
            type: 'autogenerated',
            dirName: 'departments/medical_department',
          },  
        ]
      },
      {
        type: 'category',
        label: 'Scientific Department',
        items: [
          {
            type: 'autogenerated',
            dirName: 'departments/scientific_department',
          },  
        ]
      },
      {
        type: 'category',
        label: 'Logistics Department',
        items: [
          {
            type: 'autogenerated',
            dirName: 'departments/logistics_department',
          },  
        ]
      },
      {
        type: 'category',
        label: 'Engineering & Technical Services',
        items: [
          {
            type: 'autogenerated',
            dirName: 'departments/ents_department',
          },  
        ]
      },
      {
        type: 'category',
        label: 'Mobile Task Forces',
        items: [
          {
            type: 'autogenerated',
            dirName: 'departments/mtf_department',
          },  
        ]
      }
    ],
  },],
};
