/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  supremeGuidelines: [{ type: 'autogenerated', dirName: 'supreme' }],
  departmentGuidelines: [    {
    type: 'category',
    label: 'Departmental Guidelines',
    collapsible: false,
    collapsed: false,
    items: [
      'departments/intro',
      {
        type: 'category',
        label: 'Security Department',
        items: [
          'departments/security_department/intro',
          'departments/security_department/ethics',
          'departments/security_department/installation_defense',
          'departments/security_department/installation_protocols',
          'departments/security_department/recontainment',
          'departments/security_department/roll_call',
          'departments/security_department/breach_shelter',
          'departments/security_department/hostages',
          'departments/security_department/raid_procedures',
          'departments/security_department/class_d_schedule',
          'departments/security_department/termination_criteria',
          'departments/security_department/checkpoint_protocols',
          'departments/security_department/testing_regulations',
          'departments/security_department/chain_of_command',
          'departments/security_department/punishments',
          'departments/security_department/trainings',
          'departments/security_department/miscellaneous'
        ]
      },
    ],
  },],
};
